### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by dovalid** [AgoraSpaceDAO/agora-frontend#38]
There're no designs for mobile view. Feel free to experiment and implement the UI for mobile and every possible screen size as you think it fits best. I think this issue can sum the progress of everything we have currently becoming responsive, you should just open different PRs for different parts of the app, that's where the relevant communication will go.

**Comment by KovJonas** [comment]
I changed the design of the `Level` component on mobile, it looks better this way (at least in my opinion). Let me know what's your opinion on the overall UI design of the site on smaller screens!

**Comment by KovJonas** [comment]
I made the following changes after our meeting today:
- First of all, changed the margins/paddings/spacings on the layout in a couple of places, so now the cards are wider on small, mobile screens (space utilization goes brrr)
- Switched the order of the components on the header, and also played with the font size, so now the title is smaller on mobile, and the "Connect to a wallet" button is on the top right section of the screen, as we discussed before
- I also reworked the `ActionCard` component. Now it accepts a boolean prop called `withAccordion`, and if you pass it, the card will only show its title initially, and you can open it, so you can reveal its content too. All this logic is handled in the `ActionCard` component, so I haven't changed the markup in the `Platforms`/`Staked` components!
- Last but not least, I worked on the `Level` component. I played with the spacings inside it, and now the "You have access"/"Wallet not connected" texts aren't visible on mobile (so we can display the images on the left side instead!), but you can see a checkmar or an x icon next to the level's name, with a tooltip on focus state
- *Note: I'll need to fix the appearance of the outlines in focus state.*

I'll work on the modal appearance later today, and keep you updated on that too!

**Comment by KovJonas** [comment]
Update:
- Decreased the padding on the modals under mobile, and changed the animation on them.
- The modals will appear on the bottom of the screen on mobile (just like the built in menu on most smartphones)
- Still haven't managed to solve the issue with the focus ring and the icons inside the `Tooltip` component, but we can talk about it later

**Comment by KovJonas** [comment]
- I managed to add the focus ring with box shadow, just like on the other Chakra UI components.
- I realized that the `forwardRef` issue was caused by the `Platforms` component, and not by the tooltips and icons in the `Level` component, but I fixed that too now!

**Comment by KovJonas** [comment]
I decided to play a bit with the spacings on the community page instead of just putting the "Platforms" and "Staked" sections under the levels, because I feel like those are pretty important and they shouldn't be at the bottom of the page. This way, the users can see the first 2 levels even on smaller mobiles, and they can still find the join TG/DC buttons pretty easily.

![agora-community-page](https://user-images.githubusercontent.com/53289941/125120252-7f74ca80-e0f2-11eb-9793-e62692f42a8f.PNG)
